"""
Scheduling utilities for Sports Connect Automation
"""
import os
import sys
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


class AutomationScheduler:
    """Create scheduling scripts for automation"""
    
    @staticmethod
    def create_batch_file(output_path: str = "run_sports_connect.bat",
                         python_path: str = None,
                         script_path: str = None) -> bool:
        """
        Create a batch file for Windows Task Scheduler
        
        Args:
            output_path: Path for batch file
            python_path: Path to Python executable
            script_path: Path to main script
            
        Returns:
            True if successful
        """
        if python_path is None:
            python_path = sys.executable
        
        if script_path is None:
            script_path = Path(__file__).parent.parent / "main.py"
        
        batch_content = f"""@echo off
REM Sports Connect Automation Batch File
REM Generated by AutomationScheduler

echo ========================================
echo Sports Connect Automation
echo ========================================
echo.
echo Start Time: %date% %time%
echo.

REM Change to script directory
cd /d "{os.path.dirname(os.path.abspath(script_path))}"

REM Activate virtual environment if it exists
if exist "..\\venv\\Scripts\\activate.bat" (
    call "..\\venv\\Scripts\\activate.bat"
)

REM Run the automation
"{python_path}" "{script_path}" %*

REM Capture exit code
set EXIT_CODE=%ERRORLEVEL%

echo.
echo End Time: %date% %time%
echo Exit Code: %EXIT_CODE%

REM Log to file
echo %date% %time% - Exit Code: %EXIT_CODE% >> automation_runs.log

REM Pause only if running interactively
if "%1"=="" pause

exit /b %EXIT_CODE%
"""
        
        try:
            with open(output_path, 'w') as f:
                f.write(batch_content)
            logger.info(f"Created batch file: {output_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to create batch file: {e}")
            return False
    
    @staticmethod
    def create_powershell_script(output_path: str = "run_sports_connect.ps1") -> bool:
        """
        Create a PowerShell script for scheduling
        
        Args:
            output_path: Path for PowerShell script
            
        Returns:
            True if successful
        """
        ps_content = '''# Sports Connect Automation PowerShell Script
# Generated by AutomationScheduler

$ErrorActionPreference = "Stop"
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$logDir = Join-Path $scriptPath "logs"
$logFile = Join-Path $logDir "automation_$(Get-Date -Format 'yyyyMMdd').log"

# Ensure log directory exists
if (!(Test-Path $logDir)) {
    New-Item -ItemType Directory -Path $logDir | Out-Null
}

function Write-Log {
    param($Message, $Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "$timestamp [$Level] $Message"
    Add-Content -Path $logFile -Value $logMessage
    
    switch ($Level) {
        "ERROR" { Write-Host $logMessage -ForegroundColor Red }
        "WARNING" { Write-Host $logMessage -ForegroundColor Yellow }
        "SUCCESS" { Write-Host $logMessage -ForegroundColor Green }
        default { Write-Host $logMessage }
    }
}

Write-Log "Starting Sports Connect Automation"

try {
    # Change to script directory
    Set-Location $scriptPath
    
    # Activate virtual environment if it exists
    $venvActivate = Join-Path $scriptPath ".." "venv" "Scripts" "Activate.ps1"
    if (Test-Path $venvActivate) {
        & $venvActivate
    }
    
    # Run the Python script
    $mainScript = Join-Path $scriptPath "main.py"
    & python $mainScript
    
    if ($LASTEXITCODE -eq 0) {
        Write-Log "Automation completed successfully" -Level "SUCCESS"
        
        # Optional: Send success notification
        # Send-MailMessage -To "admin@company.com" -Subject "Sports Connect Export Success" -Body "Reports exported successfully"
    } else {
        Write-Log "Automation failed with exit code: $LASTEXITCODE" -Level "ERROR"
        
        # Optional: Send failure notification
        # Send-MailMessage -To "admin@company.com" -Subject "Sports Connect Export Failed" -Body "Export failed with code $LASTEXITCODE"
    }
} catch {
    Write-Log "Error running automation: $_" -Level "ERROR"
    exit 1
}
'''
        
        try:
            with open(output_path, 'w') as f:
                f.write(ps_content)
            logger.info(f"Created PowerShell script: {output_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to create PowerShell script: {e}")
            return False
    
    @staticmethod
    def create_task_scheduler_xml(task_name: str = "Sports Connect Automation",
                                 script_path: str = None,
                                 schedule: str = "daily",
                                 start_time: str = "07:00") -> str:
        """
        Create Windows Task Scheduler XML configuration
        
        Args:
            task_name: Name of the scheduled task
            script_path: Path to script to run
            schedule: Schedule type (daily, weekly, monthly)
            start_time: Time to run (HH:MM format)
            
        Returns:
            XML content as string
        """
        if script_path is None:
            script_path = os.path.abspath("run_sports_connect.bat")
        
        # Generate schedule XML based on type
        if schedule == "daily":
            schedule_xml = f"""
    <CalendarTrigger>
      <StartBoundary>2024-01-01T{start_time}:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay>
        <DaysInterval>1</DaysInterval>
      </ScheduleByDay>
    </CalendarTrigger>"""
        elif schedule == "weekly":
            schedule_xml = f"""
    <CalendarTrigger>
      <StartBoundary>2024-01-01T{start_time}:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByWeek>
        <DaysOfWeek>
          <Monday />
          <Wednesday />
          <Friday />
        </DaysOfWeek>
        <WeeksInterval>1</WeeksInterval>
      </ScheduleByWeek>
    </CalendarTrigger>"""
        else:  # monthly
            schedule_xml = f"""
    <CalendarTrigger>
      <StartBoundary>2024-01-01T{start_time}:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByMonth>
        <DaysOfMonth>
          <Day>1</Day>
          <Day>15</Day>
        </DaysOfMonth>
        <Months>
          <January /><February /><March /><April />
          <May /><June /><July /><August />
          <September /><October /><November /><December />
        </Months>
      </ScheduleByMonth>
    </CalendarTrigger>"""
        
        xml_content = f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2024-01-01T00:00:00</Date>
    <Author>Sports Connect Automation</Author>
    <Description>Automated export of Sports Connect reports</Description>
  </RegistrationInfo>
  <Triggers>{schedule_xml}
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT4H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>{script_path}</Command>
      <WorkingDirectory>{os.path.dirname(script_path)}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>"""
        
        return xml_content
    
    @staticmethod
    def create_cron_script(output_path: str = "sports_connect_cron.sh") -> bool:
        """
        Create a shell script for cron (Linux/Mac)
        
        Args:
            output_path: Path for shell script
            
        Returns:
            True if successful
        """
        shell_content = '''#!/bin/bash
# Sports Connect Automation Shell Script
# Generated by AutomationScheduler

# Set up environment
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LOG_DIR="$SCRIPT_DIR/logs"
LOG_FILE="$LOG_DIR/automation_$(date +%Y%m%d).log"

# Ensure log directory exists
mkdir -p "$LOG_DIR"

# Function to log messages
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

log_message "Starting Sports Connect Automation"

# Change to script directory
cd "$SCRIPT_DIR"

# Activate virtual environment if it exists
if [ -f "../venv/bin/activate" ]; then
    source "../venv/bin/activate"
fi

# Run the Python script
python main.py

# Check exit code
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    log_message "Automation completed successfully"
else
    log_message "Automation failed with exit code: $EXIT_CODE"
fi

exit $EXIT_CODE
'''
        
        try:
            with open(output_path, 'w', newline='\n') as f:
                f.write(shell_content)
            
            # Make executable
            os.chmod(output_path, 0o755)
            
            logger.info(f"Created shell script: {output_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to create shell script: {e}")
            return False
    
    @staticmethod
    def show_scheduling_instructions():
        """Display instructions for scheduling the automation"""
        instructions = """
Scheduling Instructions
======================

Windows Task Scheduler:
1. Run: taskschd.msc
2. Click "Create Basic Task"
3. Name: "Sports Connect Automation"
4. Trigger: Daily (or your preference)
5. Action: Start a program
6. Program: run_sports_connect.bat
7. Start in: [directory containing the script]

Windows (using XML):
1. Save the XML configuration to a file
2. Run: schtasks /create /xml "task.xml" /tn "Sports Connect Automation"

Linux/Mac (cron):
1. Run: crontab -e
2. Add line for daily at 7 AM: 0 7 * * * /path/to/sports_connect_cron.sh
3. Save and exit

PowerShell Task:
1. Use Task Scheduler with action: powershell.exe
2. Arguments: -ExecutionPolicy Bypass -File "path\\to\\run_sports_connect.ps1"
"""
        print(instructions)
        return instructions
